updated test script to provide more information on failures.

diff --git a/tests/alltests b/tests/alltests
--- a/tests/alltests
+++ b/tests/alltests
@@ -3,6 +3,34 @@
 ritc="../../bin/Debug/ritc"
 rsl=".."
 
+details() {
+  #compile .rit file
+  bash -c "$ritc $1 >/dev/null 2>/dev/null"
+  
+  #compile out.c
+  bash -c "gcc -I$rsl out.c -lm >/dev/null 2>$1.my.out"
+  
+  if [ $? -ne 0 ]; then
+    printf "   C code file couldn't be compiled.\n" "$1"
+    printf "   See \"%s.my.out\"\n" "$1"
+    printf "   and \"out.c\"\n"
+    return
+  fi
+  
+  #run a.out
+  bash -c "./a.out >$1.my.out 2> /dev/null"
+  
+  #compare output of a.out to expected.
+  paste -d@ $1.target $1.my.out | while IFS='@' read -r f1 f2 || [[ -n "$line" ]]
+  do
+    if [ "$f1" = "$f2" ]; then
+      printf ""
+    else
+      printf "   Expected: %s; Received: %s\n" "$f1" "$f2"
+    fi
+  done
+}
+
 runtest() {
   #compile .rit file
   bash -c "$ritc $1 >/dev/null 2>/dev/null"
@@ -12,6 +40,7 @@ runtest() {
   
   if [ $? -ne 0 ]; then
     printf "FAILED: %s\n" "$1"
+    details $1
     return
   fi
   
@@ -21,11 +50,11 @@ runtest() {
   #compare output of a.out to expected.
   cmp $1.target $1.my.out > /dev/null 2> /dev/null
   if [ $? -eq 0 ]; then
-    printf "pass:   "
+    printf "pass:   %s\n" "$1"
   else
-    printf "FAILED: "
+    printf "FAILED: %s\n" "$1"
+    details $1
   fi
-  printf "%s\n" "$1"
 }
 
 echo "Delete previous test results?"
